### ISSUE TITLE
Suggestion: Buttons on main view should lead to other views

### ISSUE THREAD

**Issue by Luggs123** [bhbr/MQKB#18]
By this, I mean something like what happens on the default iOS keyboard when pushing the "123" button - rather than tap & hold to select individual letters as it is now, show a new keyboard view with all the intended letters plainly visible. This would make the interface a lot simpler and more intuitive.

**Comment by bhbr** [comment]
I has thought about this, but decided against it bc this wd mean constantly switching btw diff keyboards. Maybe if the keyboards are not persistent, i. e. switch back automatically after a key has been selected, except for the plain text one (upright letters).

What do the others think?

Another possibility: show the input options immediately, without the 0.3s delay as it does now. The last selected input (which is the input if just button is pressed and none of the input options) could maybe be highlighted in some fashion among the input options.
