### ISSUE TITLE
"Shift" Key no longer functional with version 0.21 (1)

### ISSUE THREAD

**Issue by Luggs123** [bhbr/MQKB#19]
With the most recent update, the shift key has stopped working, and clears the text. Additionally, pushing the shift key a few times in a short time closes the keyboard entirely.

In the following video (which I have had to convert to GIF), I do nothing but push the shift key a few times.

![](https://im2.ezgif.com/tmp/ezgif-2-8bb50478aa.gif)

**Comment by bhbr** [comment]
Uh, well this is embarassing. I will fix it asap, which is Monday. Until then, revert ot v0.1 😔

**Comment by bhbr** [comment]
Fixed!
